# 2. Demographics Statistics

In [1]:
source("../util/packages.R")
source("../util/variables.R")
ALL_PARTICIPANTS_METADATA <- read_rds("../R-table/ALL_PARTICIPANTS_METADATA.rds")

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   4.0.2     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘sjPlot’


The following object is masked from ‘package:ggplot2’:

    set_theme


Loading required package: lme4

Loading required package: Matrix


Attaching package: ‘Matrix’


The following objects are masked from ‘package:tidyr’:

    expand, pack, unpack



Attaching package: ‘lmerTest’


The following object is masked from ‘package:lme4’:

    lmer


The following object is masked from ‘package:stats’:

    step



Attaching package: ‘HLMdiag’


The following object is masked from ‘package:stats’:

    covratio



Attaching package: ‘data.table’


The following objects are masked from ‘package:lubridate’:

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year


The following objects are masked from ‘package:dplyr’:

    between, first, last


The following object is masked from ‘package:purrr’:

    transpose



Attaching package: ‘plotly’


The following object is masked from ‘package:ggplot2’:

    last_plot


The following object is masked from ‘package:stats’:

    filter


The following object is masked from ‘package:graphics’:

    layout


Welcome to emmeans.
Caution: You lose important information if you filter this package's results.
See '? untidy'


Attaching package: ‘reshape2’


The following objects are masked from ‘package:data.table’:

    dcast, melt


The following object is masked from ‘package:tidyr’:

    smiths



Attaching package: ‘cosinoRmixedeffects’


The following object is masked from ‘package:limma’:

    strsplit2



Attaching package: ‘kableExtra’


The following object is masked from ‘package:dplyr’:

    group_rows



Attaching package: ‘hms’


The following object is masked from ‘package:lubridate’:

    hms

In [2]:
summary_tbl <- ALL_PARTICIPANTS_METADATA |>
  distinct(pseudonym, .keep_all = TRUE) |>
  summarise(
    n_participants = n_distinct(pseudonym),
    n_male = sum(biological_sex == "Male"),
    n_female = sum(biological_sex == "Female"),
    bmi_mean = mean(as.numeric(bmi), na.rm = TRUE),
    bmi_sd = sd(as.numeric(bmi), na.rm = TRUE)
  )

summary_tbl

# Age group counts
age_counts <- ALL_PARTICIPANTS_METADATA |>
  distinct(pseudonym, .keep_all = TRUE) |>
  count(age_group)

age_counts

  n_participants n_male n_female bmi_mean bmi_sd
1 41             26     15       23.19188 3.207001

  age_group n
1 18-20     14
2 21-25     26
3 31-35      1